# Generated by Django 5.0.7 on 2024-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfil_camara_comercio_perfil_cedula_rl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('centro_costo', models.CharField(max_length=50)),
                ('producto_servicio', models.CharField(max_length=100)),
                ('vlr_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retencion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_entrega', models.DateTimeField(verbose_name='Día y Hora de Entrega')),
                ('nombre', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('centro_costo', models.CharField(choices=[('ADMINISTRACIÓN', 'ADMINISTRACIÓN'), ('PRODUCCION', 'PRODUCCION'), ('ALEVINERA', 'ALEVINERA'), ('ECOPEZ', 'ECOPEZ'), ('FERRY', 'FERRY'), ('CARRO VNS228', 'CARRO VNS228'), ('CARRO WGY', 'CARRO WGY'), ('CARRO THS 473', 'CARRO THS 473'), ('CARRO PESCA SRP 254', 'CARRO PESCA SRP 254'), ('TERMOKIN GQZ 727', 'TERMOKIN GQZ 727'), ('TERMOKIN GRK 030', 'TERMOKIN GRK 030'), ('THERMO KING THS 592', 'THERMO KING THS 592'), ('UNIDAD COMERCIALIZACION', 'UNIDAD COMERCIALIZACION')], max_length=200)),
                ('destino', models.CharField(choices=[('ADMINISTRACIÓN', 'ADMINISTRACIÓN'), ('PRODUCCION', 'PRODUCCION'), ('ALEVINERA', 'ALEVINERA'), ('ECOPEZ', 'ECOPEZ'), ('FERRY', 'FERRY'), ('CARRO VNS228', 'CARRO VNS228'), ('CARRO WGY', 'CARRO WGY'), ('CARRO THS 473', 'CARRO THS 473'), ('CARRO PESCA SRP 254', 'CARRO PESCA SRP 254'), ('TERMOKIN GQZ 727', 'TERMOKIN GQZ 727'), ('TERMOKIN GRK 030', 'TERMOKIN GRK 030'), ('THERMO KING THS 592', 'THERMO KING THS 592'), ('UNIDAD COMERCIALIZACION', 'UNIDAD COMERCIALIZACION')], max_length=200)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('codigo_cotizacion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('empresa', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('tiempo_entrega', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('destino', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('solicitado', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='camara_comercio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula_rl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='certificado_bancario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
