# Generated by Django 5.0.7 on 2024-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_anticipo_diario_orden_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
